### ISSUE TITLE
Does not transform private fields declared in constructor

### ISSUE THREAD

**Issue by janousek** [timocov/ts-transformer-minify-privates#10]
This simple case does not transform:
```
class Test {
    constructor(private tmp: any) { }
    public get() { return this.tmp; }
}
```

**Comment by timocov** [comment]
Heh, nice catch. If you wish you can provide a PR with the fix. If not, then I'll see into it in couple of days.

**Comment by timocov** [comment]
[Version 0.2.0](https://www.npmjs.com/package/ts-transformer-minify-privates/v/0.2.0) is just published!
