### ISSUE TITLE
Deprecated API warning: 'createIdentifier' has been deprecated since v4.0.0

### ISSUE THREAD

**Issue by noname0310** [timocov/ts-transformer-minify-privates#19]
```
DeprecationWarning: 'createIdentifier' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.

DeprecationWarning: '' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
```
There's a deprecation warning Please solve it

**Comment by timocov** [comment]
@noname0310 this was done intentionally to support previous versions of the compiler. I think once the compiler reaches v5 we can upgrade the minimal supported version to 4 and replace this usage. Thanks for reporting!

**Comment by noname0310** [comment]
Thank you for your answer I'm using it really well. I hope this Transformer will continue to be available in the future.

**Comment by timocov** [comment]
Fixed in https://github.com/timocov/ts-transformer-minify-privates/releases/tag/v1.0.0
