### ISSUE TITLE
Usage with babel-loader?

### ISSUE THREAD

**Issue by yvele** [timocov/ts-transformer-minify-privates#20]
I'm using [babel-preset-typescript](https://babeljs.io/docs/en/babel-preset-typescript) (with [babel-plugin-transform-typescript](https://babeljs.io/docs/en/babel-plugin-transform-typescript)).

Is it possible to use your transformer with or without an extra [ts-loader](https://github.com/TypeStrong/ts-loader) step?

Any babel usage sample?

Thank you for your great lib btw.

**Comment by yvele** [comment]
Or is it possible to easily get a [`ts.Program`](https://github.com/microsoft/TypeScript/blob/main/src/compiler/program.ts) instance using native typescript ?

**Comment by timocov** [comment]
Hi @yvele,

I haven't worked with babel ts plugin, but from what I've seen is that they don't use compilation internally but transpilation only. This tool cannot work if there is no compilation and the type check was happened.
